### ISSUE TITLE
Player crashes immediately after joining or ends up in infinite loop

### ISSUE THREAD

**Issue by itsdinkd** [kyrptonaught/shulkerupgrades#3]
1.17.1 / Fabric / Latest version of Upgradeable Shulkers

[20:25:14] [REI-ReloadPlugins/ERROR]: UpgradedShulkersREIPlugin plugin failed to reloadable-plugin-DisplayRegistryImpl!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3494.method_15138()" because "this.field_9022" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52) ~[?:?]
	at net.minecraft.recipe.Ingredient$TagEntry.getStacks(Ingredient:207) ~[?:?]
	at net.minecraft.recipe.Ingredient.method_8104(Ingredient:50) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at net.minecraft.recipe.Ingredient.cacheMatchingStacks(Ingredient:50) ~[?:?]
	at net.minecraft.recipe.Ingredient.getMatchingStacks(Ingredient:44) ~[?:?]
	at me.shedaniel.rei.api.common.util.EntryIngredients.ofIngredient(EntryIngredients.java:106) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.api.common.util.EntryIngredients.ofIngredients(EntryIngredients.java:130) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.plugin.common.displays.crafting.DefaultShapelessDisplay.<init>(DefaultShapelessDisplay.java:35) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at net.kyrptonaught.upgradedshulker.compat.UpgradedShulkersREIPlugin.registerColorRecipe(UpgradedShulkersREIPlugin.java:47) ~[upgradedshulkers-1.0.2.-1.17.jar:?]
	at net.kyrptonaught.upgradedshulker.compat.UpgradedShulkersREIPlugin.registerDisplays(UpgradedShulkersREIPlugin.java:35) ~[upgradedshulkers-1.0.2.-1.17.jar:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:62) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.registry.display.DisplayRegistryImpl.acceptPlugin(DisplayRegistryImpl.java:47) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:59) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$0(PluginManagerImpl.java:193) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:145) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:193) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:129) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$reloadPlugins$22(RoughlyEnoughItemsCoreClient.java:378) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by rmonk** [comment]
I suddenly started getting this same error today.  I was wandering around in the Bumblezone on Better Minecraft [ FABRIC ] 1.18 v8.5 and got disconnected.  When I rejoin I get this exact error and am kicked back out.
